Dp 315 - Try to add required fields to the connector and show in two different divs
dreamfactorysoftware/df-admin-app pull request #239
Opened 2021-05-19 13:21 UTC by alex-504

2021-05-25 08:15 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                    console.log(scope.serviceInfo);
@alex-504 Can you delete this console.log?

2021-05-25 08:44 UTC, alex-504 commented on app/admin_components/adf-services/dreamfactory-services.js
> +                    console.log(scope.serviceInfo);
Sure. Done!

2021-06-01 15:09 UTC, yaroslavmo requested changes

2021-06-01 15:09 UTC, yaroslavmo commented on app/admin_components/adf-services/views/df-service-config.html
> +    <div ng-if="selectedSchema.name === 'pgsql'" ng-include="'admin_components/adf-services/views/df-service-pgsql.html'"></div>
Nothing would change if we write
`<div 
ng-if="selectedSchema.name === 'mysql' || selectedSchema.name === 'sqlsrv' || selectedSchema.name === 'oracle' || selectedSchema.name === 'pgsql' " 
ng-include="'admin_components/adf-services/views/df-service-pgsql.html'">`

or am I wrong?

2021-06-01 15:09 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                scope.serviceField = true;
If the variable is boolean, the name should start with `is` or `has`. 

Also, I don't think serviceField is ever used anywhere.

2021-06-02 08:08 UTC, yaroslavmo requested changes

2021-06-02 08:08 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                scope.serviceField = true;
Remove

2021-06-08 07:20 UTC, yaroslavmo commented
Use DP-315-test branch instead

2021-06-08 07:20 UTC, closed without merging