DP-338 - Make Service Page Into a Dashboard
dreamfactorysoftware/df-admin-app pull request #253
Opened 2021-06-15 11:49 UTC by tomonorman

This will be tied to DP-338 branch in df-api-docs-ui
https://github.com/dreamfactorysoftware/df-api-docs-ui/compare/develop...DP-338

cc and kudos to @alex-504

2021-06-16 02:23 UTC, tomonorman commented
The 4.7 release commit, unless I'm going crazy, wasnt there before when comparing this branch to develop. Is it due to the 4.8 release?

2021-06-16 02:33 UTC, tomonorman commented on app/admin_components/adf-services/views/df-service-info.html
> +                <a ng-click="goToSelectedServiceScripts(serviceInfo)" style="cursor: pointer;">Scripted Endpoints associated with {{ serviceInfo.name }}</a>
@wjgilmore kindly pointed out that scripts and remote service wont support scripted endpoints. However a page does still show on the scripts tab (without functionality). This is what the link from the services tab will go to.

The same goes for LDAP, SSO, Notification, and some of the OAuth (eg twitter doesnt, but google does).

So should we just hide this link for these service types? an ng-hide if serviveinfo.type (or something similar) would do the job. Or just allow it to go to the endpoint screen (without functionality) in the same manner as how you can do so from the scripts tab at the moment?

2021-06-16 16:44 UTC, yaroslavmo requested changes
I skipped HTML files for the first review as I did not pull the branch. Let's fix js first and then deal with how it looks.

2021-06-16 16:44 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +            selectedRelatedRole: null
The name `selectedRelatedRole` does not specifically tell to what this role is related and I think we would only refer to it as `dfSelectedService.selectedRelatedRole` so the word `selected` is doubled.
Consider naming it just `relatedRole` so the call to it would be `dfSelectedService.relatedRole`.

2021-06-16 16:44 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                        params: {"related": "role_service_access_by_role_id,lookup_by_role_id"}
Reminder to myself: 
look at how roles are loaded on the roles tab and how they will not be loaded again if we switch tabs. Here we load roles every time user clicks on the service from the list. We need to get rid of this behaviour so they are not requested everytime we click service.

I will show you how I see it at the meeting.

2021-06-16 16:44 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                            var currentServiceID = scope.currentEditService.id;
Stick to the naming convention.  currentServiceID -> currentServiceId

2021-06-16 16:44 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                var roleServiceAccessArray = role.role_service_access_by_role_id
roleServiceAccessArray -> roleServiceAccessList.  It is a better name because js does not have List datatype so it would never interfere.

2021-06-16 16:44 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                if (roleServiceAccessArray.length != 0) {
Always use strict comparison `!==`. Use non-strict comparison only in special cases.

2021-06-16 16:44 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                    roleServiceAccessArray.forEach(function (service) {
Use special Array.filter js method to filter stuff.

2021-06-16 16:44 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                        name: scope.serviceInfo.name
Will currentService object always have just one property name? if so then it would better to name it currentServiceName

2021-06-16 16:44 UTC, yaroslavmo commented on app/admin_components/adf-utility/dreamfactory-utility.js
> +                        scope.setActiveView(scope.links[1]);
What is a magic number '1' ?

This question would be asked by anyone who sees this.

2021-06-16 16:44 UTC, yaroslavmo commented on app/admin_components/adf-utility/dreamfactory-utility.js
> +                        scope.setActiveView(scope.links[1]);
Better create a variable with a descriptive name.

2021-06-16 16:44 UTC, yaroslavmo commented on app/scripts/app.js
> +    .constant('APP_VERSION', '4.7.0')
we now have 4.8.0. PR's branch needs to be rebased to develop.

2021-06-23 02:03 UTC, tomonorman commented on app/admin_components/adf-roles/dreamfactory-roles.js
> +                var init = function () {
Done

2021-06-23 03:40 UTC, tomonorman commented on app/admin_components/adf-scripts/dreamfactory-scripts.js
> +                        setTimeout(init, 300);
Yeah, sorry that makes much more sense. This is done

2021-06-23 03:45 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +            selectedRelatedRole: null
Done

2021-06-23 04:01 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                        params: {"related": "role_service_access_by_role_id,lookup_by_role_id"}
Yup you are correct, we can just have apiData also load in "role", and just remove the get request. Done

2021-06-23 04:03 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                            var currentServiceID = scope.currentEditService.id;
Done!

2021-06-23 04:05 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                var roleServiceAccessArray = role.role_service_access_by_role_id
Done!

2021-06-23 04:14 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                if (roleServiceAccessArray.length != 0) {
My bad, done

2021-06-23 05:57 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                    roleServiceAccessArray.forEach(function (service) {
Thanks for that. Took me a while to work out, but yup, the filter function is way cleaner, got it down to 3 lines.

2021-06-23 06:40 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                        name: scope.serviceInfo.name
You're correct, changed

2021-06-23 06:46 UTC, tomonorman commented on app/admin_components/adf-utility/dreamfactory-utility.js
> +                        scope.setActiveView(scope.links[1]);
Done!

2021-06-23 06:55 UTC, tomonorman commented on app/admin_components/adf-scripts/dreamfactory-scripts.js
> +                dfSelectedService.currentService = null;
Done! Thanks for the tip

2021-06-23 06:55 UTC, tomonorman commented on app/scripts/app.js
> +    .constant('APP_VERSION', '4.7.0')
Will rebase and push

2021-06-24 12:31 UTC, yaroslavmo requested changes
We need to improve the design. It is not clear that links are clickable.

2021-06-24 12:31 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +            RelatedRole: null,
Also it is not consistent

2021-06-25 03:43 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +            RelatedRole: null,
typo, my bad

2021-06-25 06:50 UTC, tomonorman commented
Added some styling. Let me know what you think

2021-08-05 13:17 UTC, yaroslavmo reviewed
@tomonorman If we merge these changes without df-api-docs ones is it still going to work?

2021-08-05 13:17 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                    getRelatedRoles();
this should be:
`scope.$root.relatedRoles = getRelatedRoles();`

Because the name `getRelatedRoles` is supposed to only return roles array.

2021-08-05 13:47 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                    getRelatedRoles();
ah right. @yaroslavmo Just to confirm you mean the line 178 should just be a `return relatedRoles` and then we just assign it to `scope.$root.relatedRoles = getRelatedRoles()`

2021-08-05 13:48 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                    scope.$root.relatedRoles = relatedRoles;
@yaroslavmo this should just return, not assign right?

2021-08-05 13:51 UTC, tomonorman commented
@yaroslavmo Yes it doesnt need df-api-docs changes -> the html only links to the api docs tab (not to a particular doc).
and all the previous js that was used to go to a particular doc was directly in the api-docs repo, so as long as we dont include those changes, other things wouldnt be affected

2021-08-19 11:53 UTC, merged