DP-342 Test Datasource Upon Service Creation
dreamfactorysoftware/df-admin-app pull request #257
Opened 2021-07-01 09:42 UTC by tomonorman

2021-07-28 16:32 UTC, yaroslavmo requested changes

2021-07-28 16:32 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                        }
Lines 664-666 are identical to these.

2021-07-28 16:32 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
>                                  };
Why don't just remove this first `then` as you still added a new one with testServiceConnection after it?

2021-07-28 16:32 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +
remove space

2021-07-28 16:32 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                }
the code is identical to the save request?  You should have moved it to a function.

2021-07-29 11:33 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                message: 'However Test Connection Failed: ' + reject.data.error.message
DOne

2021-07-29 11:34 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +
done

2021-07-29 11:34 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +
sorry

2021-07-29 11:40 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
>                                  };
Sorry, I'm not following this one -> this github preview is just showing some blank lines.
Do you mean the `then`  on line 614, 640, and 647? I needed to chain these thens as the calls to the backend are all asynchrous so needed to chain the promises to stop one returning before a different one (i.e keep the order the same). 

So each function is returning a result, which its passing to the next one. 

Or am i up the wrong tree?

2021-07-29 12:14 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                        }
moved the stuff above it into a function, and now this conditional is called after the function completes

2021-07-29 12:14 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                }
whoopsy, done

2021-07-29 12:19 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +
done

2021-08-05 12:45 UTC, yaroslavmo requested changes

2021-08-05 12:45 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
>                                  };
Yeah sorry got lost in the callback hell

2021-08-05 12:45 UTC, yaroslavmo commented on app/admin_components/adf-services/dreamfactory-services.js
> +                    var displayServiceConnectionNotification = function (messageOptions) {
`displayServiceConnectionNotification` is a bad name for this function as it is not only displaying but actually doing the request.

`testServiceConnection` is way better but I see that you used it inside of the function.
I suggest renaming your current testServiceConnection to something like `testServiceSchema` and call the main function `testServiceConnection`

2021-08-06 06:24 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                        return scope.selectedSchema.group == 'Database';
oops, sorry, done

2021-08-06 06:38 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                    var displayServiceConnectionNotification = function (messageOptions) {
Good call, done

2021-08-06 06:40 UTC, tomonorman commented on app/admin_components/adf-services/dreamfactory-services.js
> +                                    messageOptions.type === 'success' ? dfNotify.success(messageOptions) : dfNotify.error(messageOptions);
ah yeah. Done

2021-08-06 12:58 UTC, yaroslavmo commented
@tomonorman I found another bug. Here is the flow:
When I am trying to create a service with the same namespace that already exists in the system I expect an error saying that there is a duplicate entry:
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test' for key` 
But this error is overwritten with an error from your test request.

The only way how we can fix that is to create a button "test connection" so users would click on it instead of doing this test automatically. This way we would not slip into dreamfactory flow and overwrite any important notifications.

2021-08-13 08:48 UTC, tomonorman commented
HI @yaroslavmo 
My latest commit has a check whether the initial save was succesful or not. If it wasnt, then it will ignore the testing logic and just output the error (as it used to do)

This should get rid of any issues with the test overwriting a failed save?

2021-09-02 15:19 UTC, yaroslavmo approved these changes

2021-09-02 15:23 UTC, merged